### ISSUE TITLE
이미지 클롤링

### ISSUE THREAD

**Issue by TaeHoon403** [Team-Coma/eat-together#65]
- 모임 검색 마다 이미지 클롤링 하는가 아니면 모임 테이블에 파일 테이블 연결해서 저장해두고 할건가
- 이미지 등록안된 가게 클롤링하면 에러남
- 이미지가 없는 가게들은 자체적으로 정해서 이미지 하나 띄워주는게 좋을듯해서 이미지 하나 정하기

**Comment by KimTaeHoon43** [comment]
해결
